# Generated by Django 5.2.4 on 2025-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FruitApp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fruit_images/'),
        ),
    ]
